BackendCapstone/Models/ClientPage.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BackendCapstone.Models
{
    public class ClientPage 
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string ImgPath { get; set; }
         
      
        [NotMapped]
        public List<ApplicationUser> Users { get; set; }
        [NotMapped]
        public List<ApplicationUser> ClientUsers { get; set; }

       [NotMapped]
        public StoryBoard StoryBoard { get; set; }

        public List<StoryBoard> StoryBoards { get; set; }

    }
}

BackendCapstone/Controllers/ClientPagesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BackendCapstone.Data;
using BackendCapstone.Models;
using System.IO;
using Microsoft.AspNetCore.Http;
using BackendCapstone.Models.ClientPageViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace BackendCapstone.Controllers
{
    [Authorize]
    public class ClientPagesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;

        public ClientPagesController(UserManager<ApplicationUser> userManager, ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _userManager = userManager;
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: ClientPages
        public async Task<IActionResult> Index()
        {
            var currentUser = await GetCurrentUserAsync();
            
            //Admin users see all Client Pages
            if (currentUser.UserTypeId == 1)
            {
                var allClientPages = await _context.ClientPages.ToListAsync();
                return View(allClientPages);
            }

            //Rep users see a list of their currently assigned Client Pages
            if (currentUser.UserTypeId == 2)
            {
                var assignedClientPages = await _context.ClientPageUsers
                .Where(cp => cp.UserId == currentUser.Id)
                .Select(cp => cp.ClientPage)
                .ToListAsync();
                return View(assignedClientPages);           
            }

            //So that client users cannot access other Client Pages using URL:
            return NotFound();
        }

        // GET: ClientPages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var clientPage = await _context.ClientPages
                .Include(m => m.StoryBoards)
                .FirstOrDefaultAsync(m => m.Id == id);

            var orderedStoryBoards = await _context.StoryBoards             
                .Include(sb => sb.Chats)
                .ThenInclude(c => c.User)
                .OrderBy(sb => sb.PostDateTime)
                .Where(sb => sb.ClientPageId == clientPage.Id)
                .ToListAsync();
            
            var assignedUsers = await _context.ClientPageUsers
                .Include(cpu => cpu.User)
                .Where(cpu => cpu.ClientPageId == id)
                .Select(cpu => cpu.User)
                .ToListAsync();

            

            clientPage.StoryBoards = orderedStoryBoards;
            clientPage.Users = assignedUsers;

            var viewModel = new ClientPageDetailsViewModel()
            {
                ClientPage = clientPage,             
            };

            if (clientPage == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostChat(ClientPageDetailsViewModel viewModel)
        {
            var currentUser = await GetCurrentUserAsync();

            var chat = new Chat()
            {
                Text = viewModel.ChatText,
                StoryBoardId = viewModel.StoryBoardId,
                UserId = currentUser.Id,
                Timestamp = DateTime.Now
            };
           
            if (ModelState.IsValid)
            {
                _context.Add(chat);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Details", new { Id = viewModel.ClientPage.Id });
        }

        // GET: ClientPages/Create
        public IActionResult Create()
        {
            var viewModel = new ClientPageCreateEditViewModel();
            return View(viewModel);
        }

        // POST: ClientPages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ClientPageCreateEditViewModel viewModel)
        {           
            if (ModelState.IsValid)
            {
                if (viewModel.Img != null)
                {
                    var uniqueFileName = GetUniqueFileName(viewModel.Img.FileName);
                    var imageDirectory = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                    var filePath = Path.Combine(imageDirectory, uniqueFileName);
                    using (var myFile = new FileStream(filePath, FileMode.Create))
                    {
                        viewModel.Img.CopyTo(myFile);
                    }                   
                    viewModel.ClientPage.ImgPath = uniqueFileName;
                }
                _context.Add(viewModel.ClientPage);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));         
            }
            return View(viewModel);
        }     

       

        // GET: ClientPages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clientPage = await _context.ClientPages.FindAsync(id);

            var clientUsers = await _context.ApplicationUsers
                .Where(u => u.UserTypeId == 3)
                .ToListAsync();

            var clientUserOptions = clientUsers.Select(u => new SelectListItem(u.FirstName + " " + u.LastName, u.Id)).ToList();

            var viewModel = new ClientPageCreateEditViewModel()
            {
                ClientPage = clientPage,
                ClientUsers = clientUsers,
                ClientUserOptions = clientUserOptions
            };

            
            return View(viewModel);
        }

        // POST: ClientPages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ClientPageCreateEditViewModel viewModel)
         {
            var clientPage = viewModel.ClientPage;
            if (id != clientPage.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var currentFileName = viewModel.ClientPage.ImgPath;
                    if (viewModel.Img != null && viewModel.Img.FileName != currentFileName)
                    {
                        if (currentFileName != null)
                        {
                            var images = Directory.GetFiles("wwwroot/images");
                            var fileToDelete = images.First(i => i.Contains(currentFileName));
                            System.IO.File.Delete(fileToDelete);
                        }
                        var uniqueFileName = GetUniqueFileName(viewModel.Img.FileName);
                        var imageDirectory = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                        var filePath = Path.Combine(imageDirectory, uniqueFileName);
                        using (var myFile = new FileStream(filePath, FileMode.Create))
                        {
                            viewModel.Img.CopyTo(myFile);
                        }
                        viewModel.ClientPage.ImgPath = uniqueFileName;                       
                    }
                    if (viewModel.ClientUserId != null)
                    {
                        var clientPageUser = new ClientPageUser()
                        {
                            UserId = viewModel.ClientUserId,
                            ClientPageId = viewModel.ClientPage.Id
                        };
                        _context.Add(clientPageUser);
                        await _context.SaveChangesAsync();
                    }
                    _context.Update(clientPage);
                    await _context.SaveChangesAsync();

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientPageExists(clientPage.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(clientPage);
        }


        // GET: ClientPages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clientPage = await _context.ClientPages
                .FirstOrDefaultAsync(m => m.Id == id);

            if (clientPage == null)
            {
                return NotFound();
            }

            var assignedUsers = await _context.ClientPageUsers
                .Include(cpu => cpu.User)
                .Where(cpu => cpu.ClientPageId == id)
                .Select(cpu => cpu.User)
                .ToListAsync();

            clientPage.Users = assignedUsers;


            return View(clientPage);
        }

        // POST: ClientPages/Delete/5

BackendCapstone/Views/ClientPages/Create.cshtml
@model BackendCapstone.Models.ClientPageViewModels.ClientPageCreateEditViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ClientPage</h4>
<hr />
<div class="row">
    <div class="col-md-4">

        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div> 
            <div class="form-group">
                <label asp-for="Img"></label>
                <input asp-for="Img" type="file">
                <span asp-validation-for="Img"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientPage.Name" class="control-label"></label>
                <input asp-for="ClientPage.Name" class="form-control" />
                <span asp-validation-for="ClientPage.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientPage.Description" class="control-label"></label>
                <textarea asp-for="ClientPage.Description" class="form-control"></textarea>
                <span asp-validation-for="ClientPage.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" asp-page-handler="Upload" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Client Pages</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BackendCapstone/Views/ClientPages/Delete.cshtml
@model BackendCapstone.Models.ClientPage

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this Client Page?</h3>
<div>
   
    <hr />
    <div style="display: flex; margin: 30px; width:1000px; height:315px; background-color:#FAFAFA; border-radius:3px;">
        <div style="margin: 0 15px 0 0;">
            <img style="width:300px; height:315px;" asp-append-version="true" src="~/images/@Model.ImgPath" />
        </div>
        <div style="margin:15px 0 0 0;">

            <h5>
                @Html.DisplayFor(modelItem => Model.Name)
            </h5>
            <hr />
            <p>
                @Html.DisplayFor(modelItem => Model.Description)
            </p>
            <hr />

            <div style="display:flex; flex-direction:row;">
                @foreach (var item in Model.Users)
                {
                    <div style="margin:10px 10px 10px 10px;">
                        <a asp-controller="ApplicationUsers" asp-action="MarketingUserDetails" asp-route-id="@item.Id">
                            <div style="display: flex; flex-direction: column; justify-content: center;">
                                <img style="width:70px; height: 70px; border-radius: 50%;" src="~/images/@item.ImgPath" asp-append-version="true" />
                                <p>@item.FirstName @item.LastName</p>
                            </div>
                        </a>
                    </div>
                }
            </div>
        </div>

    </div>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a href="javascript:history.go(-1)">Back to Previous Page</a>
    </form>

</div>

BackendCapstone/Views/ClientPages/Details.cshtml
@model BackendCapstone.Models.ClientPageViewModels.ClientPageDetailsViewModel
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@{var user = await UserManager.GetUserAsync(User);}

@{
    ViewData["Title"] = "Details";
}
<div class="displayFlex--row">
    <div class="clientHomeName">
        <h1>@Model.ClientPage.Name</h1>
    </div>
    <div class="clientHomeUsers">
        @foreach (var item in Model.ClientPage.Users)
        {
            <div class="userColumn">
                @if (user.UserTypeId == 3)
                {
                    
                        <img class="userImg" src="~/images/@item.ImgPath" asp-append-version="true" />
                        <p>@item.FirstName @item.LastName</p>
                   
                }
                @if (user.UserTypeId == 1)
                {
                    <a asp-controller="ApplicationUsers" asp-action="Details" asp-route-id="@item.Id">
                        <div class="clientPageDetailsUser">
                            <img class="userImg" src="~/images/@item.ImgPath" asp-append-version="true" />
                            <p>@item.FirstName @item.LastName</p>
                        </div>
                    </a>
                }
            </div>
        }
    </div>
</div>

@if (user.UserTypeId != 3)
{
    <p>
        <a class="create" asp-controller="StoryBoards" asp-action="Create" asp-route-id=@Model.ClientPage.Id>Create New Story</a>
    </p>
}

<div class="storyBoardsContainer">
    <div id="storyBoardsList" class="storyBoards">

        @*  Use for loop to render unique form elements and ids for each StoryBoard. *@
        @for (int i = 0; i < Model.ClientPage.StoryBoards.Count; i++)
        {
            @*  StoryBoard and Chat container *@
            <div class="storyBoardContainer">

                @*  StoryBoard *@
                <div class="storyBoard">

                    @*  StoryBoard Header *@
                    <div class="storyBoardHeader">
                        <p style="margin: 10px 0 0 0">
                            <em>@Model.ClientPage.StoryBoards[i].PostDateTime</em>
                        </p>
                        <div id="approvalBox--@Model.ClientPage.StoryBoards[i].Id" class="approvalBox">
                            @if (Model.ClientPage.StoryBoards[i].IsApproved == true)
                            {
                                <img id="approvalCheck--@Model.ClientPage.StoryBoards[i].Id" class="approvalCheckImg" src="~/images/checkmark.png" />
                            }
                        </div>
                    </div>

                    @*  StoryBoard Card *@
                    <div class="storyBoardClientInfo">
                        <img class="storyBoardClientImg" src="~/images/@Model.ClientPage.ImgPath" asp-append-version="true" />
                        <p><strong>@Model.ClientPage.Name</strong></p>
                    </div>
                    <div>
                        <img class="storyBoardImg" asp-append-version="true" src="~/images/@Model.ClientPage.StoryBoards[i].ImgPath" />
                    </div>
                    <div>
                        <p>
                            <strong>@Model.ClientPage.Name</strong>&nbsp;@Model.ClientPage.StoryBoards[i].Text
                        </p>
                    </div>

                    @*  Client users cannot edit or delete *@
                    @if (user.UserTypeId != 3)
                    {
                        <div class="editDeleteContainer">
                            <a asp-route-id=@Model.ClientPage.StoryBoards[i].Id asp-controller="StoryBoards" asp-action="Edit">Edit</a>&nbsp;|&nbsp;
                            <a asp-route-id=@Model.ClientPage.StoryBoards[i].Id asp-controller="StoryBoards" asp-action="Delete">Delete</a>
                        </div>
                    }
                </div>

                <div class="storyBoardChatContainer">
                    <div class="storyBoardChat">
                        <div id="messagesList--@Model.ClientPage.StoryBoards[i].Id" class="chatList">
                            @foreach (var item in Model.ClientPage.StoryBoards[i].Chats)
                            {

                                if (item.UserId == user.Id)
                                {

                                    <div class="userChat">
                                        <p style="margin: 5px;">@item.Text</p>
                                    </div>
                                }
                                if (item.UserId != user.Id)
                                {
                                    <div class="otherUserChat">
                                        <p style="margin: 5px;"><b>@item.User.FirstName @item.User.LastName</b></p>
                                        <p style="margin: 5px;">@item.Text</p>
                                    </div>
                                }
                            }
                        </div>

                        <input id="clientPageId" type="hidden" asp-for="ClientPage.Id" />
                        <input id="storyBoardId" type="hidden" value="@Model.ClientPage.StoryBoards[i].Id" asp-for="@Model.StoryBoardId" />
                        <input id="userId--@Model.ClientPage.StoryBoards[i].Id" type="hidden" value="@user.Id" />

                        <div class="chatInputContainer">
                            <input id="messageInput--@Model.ClientPage.StoryBoards[i].Id" class="chatInput" placeholder="Add a comment..." />
                            <input id="sendButton--@Model.ClientPage.StoryBoards[i].Id" type="button" value="Post" class="btn" />
                        </div>
                    </div>
                </div>
            </div>
        }
        <input id="userTypeId" type="hidden" value="@user.UserTypeId" />
    </div>
</div>
@if (user.UserTypeId != 3)
{
    <div>
        <a asp-action="Index">Back to Client Pages</a>
    </div>
}

<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/chat.js"></script>

BackendCapstone/Views/ClientPages/Edit.cshtml
@model BackendCapstone.Models.ClientPageViewModels.ClientPageCreateEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ClientPage</h4>
<hr />
<div class="row">
    <div class="col-md-4 editContainer">
        <div style="margin: 0 15px 0 0;">
            <img class="editImg" asp-append-version="true" src="~/images/@Model.ClientPage.ImgPath" />
        </div>
        <form asp-action="Edit" enctype="multipart/form-data" class="editForm">
            <div class="flex-row">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ClientPage.Id" />
                <div class="form-group">
                    <label asp-for="Img"></label>
                    <input asp-for="Img" type="file">
                    <span asp-validation-for="Img"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ClientPage.Name" class="control-label"></label>
                    <input asp-for="ClientPage.Name" class="form-control" />
                    <span asp-validation-for="ClientPage.Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ClientPage.Description" class="control-label"></label>
                    <textarea asp-for="ClientPage.Description" class="form-control"></textarea>
                    <span asp-validation-for="ClientPage.Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ClientUserId"></label>
                    <select asp-for="ClientUserId" class="form-control" asp-items="Model.ClientUserOptions"></select>
                </div>
                <div class="form-group">
                    @Html.HiddenFor(m => m.ClientPage.ImgPath)
                </div>
                <div class="form-group">
                    <input asp-page-handler="Upload" type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a href="javascript:history.go(-1)">Back to Previous Page</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BackendCapstone/Views/ClientPages/Index.cshtml
@model IEnumerable<BackendCapstone.Models.ClientPage>
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@{var user = await UserManager.GetUserAsync(User);}

@{
    ViewData["Title"] = "Index";
}

<h1>Client Pages</h1>
@if (user.UserTypeId == 1)
{ 
    <p class="create">
        <a asp-action="Create">Create New</a>
    </p>
}
<div class=clientPagesContainer>
    @foreach (var item in Model)
    {

     <div class="clientPageCard">
        <a class="clientPageCardLink" asp-controller="ClientPages" asp-action="Details" asp-route-id="@item.Id">
            <div>
                <img class="clientPageCardImg" asp-append-version="true" src="~/images/@item.ImgPath" />
            </div>
            <div class="clientPageCardName">
                <h5>
                    @Html.DisplayFor(modelItem => item.Name)
                </h5>
            </div>
        </a>
        @if (user.UserTypeId == 1)
        {
            <div class="editDeleteContainer">
                <a asp-route-id=@item.Id asp-controller="ClientPages" asp-action="Edit">Edit</a>&nbsp;|&nbsp;
                <a asp-route-id=@item.Id asp-controller="ClientPages" asp-action="Delete">Delete</a>
            </div>
        }
    </div>

    }
</div>