BackendCapstone/Models/ApplicationUser.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BackendCapstone.Models
{
    public class ApplicationUser : IdentityUser
    {
        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        public string ImgPath { get; set; }

        [Required]
        [Display(Name = "User Type")]
        public int UserTypeId { get; set; }

        public UserType UserType { get; set; }

       


    }
}

BackendCapstone/Models/ApplicationUserViewModels/EditMarketingUserViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BackendCapstone.Models.ApplicationUserViewModels
{
    public class EditMarketingUserViewModel
    {
        public string UserId {get; set;}
        
        public ApplicationUser User { get; set; }

        [Display(Name="User Type")]
        public int UserTypeId { get; set; }

        public List<SelectListItem> UserTypeOptions { get; set; }

        public List<ClientPage> AssignedClientPages { get; set; }

        public List<SelectListItem> ClientPageOptions { get; set; }

        [Display(Name = "Assign Client Page")]
        public ClientPageUser ClientPageUser { get; set; }
    }
}

BackendCapstone/Models/ApplicationUserViewModels/MarketingUserDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BackendCapstone.Models.ApplicationUserViewModels
{
    public class MarketingUserDetailsViewModel
    {
       
        public ApplicationUser User { get; set; }

        public List<ClientPageUser> ClientPageUsers { get; set; }

        public List<StoryBoard> StoryBoards { get; set; }

        public List<Message> Messages { get; set; }
    }
}

BackendCapstone/Controllers/ApplicationUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BackendCapstone.Data;
using BackendCapstone.Models;
using BackendCapstone.Models.ApplicationUserViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace BackendCapstone.Controllers
{
    [Authorize]
    public class ApplicationUsersController : Controller
    {
        private readonly IConfiguration _config;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public ApplicationUsersController(IConfiguration config, ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
            _config = config;
        }

        public SqlConnection Connection
        {
            
            get
            {
                return new SqlConnection(_config.GetConnectionString("DefaultConnection"));
            }
        }
     

        public async Task<IActionResult> Details(string id)
        {
            var user = await _context.ApplicationUsers
                .Where(u => u.Id == id)
                .FirstOrDefaultAsync();

            if (user.UserTypeId == 1 || user.UserTypeId == 2)
            {            
                return RedirectToAction("MarketingUserDetails", new { Id = user.Id });
            }

            return RedirectToAction("ClientUserDetails", new { Id = user.Id });
        }

        public async Task<IActionResult> MarketingUserDetails([FromRoute] string id)
        {
            var marketingUser = await _context.ApplicationUsers
                .Include(u => u.UserType)
                .Where(u => u.Id == id)
                .FirstOrDefaultAsync();

            var upcomingStoryBoards = await _context.StoryBoards
                .OrderBy(sb => sb.PostDateTime)
                .Include(sb => sb.ClientPage)
                .Where(sb => sb.UserId == id)
                .Take(6)
                .ToListAsync();

            var clientPageUsers = await _context.ClientPageUsers
                .Include(cp => cp.ClientPage)
                .Where(cp => cp.UserId == id).ToListAsync();          

            var viewModel = new MarketingUserDetailsViewModel()
            {
                User = marketingUser,
                StoryBoards = upcomingStoryBoards,
                ClientPageUsers = clientPageUsers
            };

            return View(viewModel);
        }

        public async Task<IActionResult> ClientUserDetails([FromRoute] string id)
        {
            var clientUser = await _context.ApplicationUsers
                .Include(u => u.UserType)
                .Where(u => u.Id == id)
                .FirstOrDefaultAsync();

            var clientPageUsers = await _context.ClientPageUsers
                .Include(cp => cp.ClientPage)
                .Where(cp => cp.UserId == id)
                .ToListAsync();       

            return View(clientUser);
        }




        public async Task<IActionResult> EditMarketingUser(string id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.ApplicationUsers
                .Where(u => u.Id == id)
                .FirstOrDefaultAsync();
            var userTypeOptions = await _context.UserTypes
                .Where(ut => ut.Id == 1 || ut.Id == 2)
                .Select(ut => new SelectListItem(ut.Type, ut.Id.ToString()))
                .ToListAsync();
            var assignedClientPages = await _context.ClientPageUsers
                .Where(cp => cp.UserId == id)
                .Select(cp => cp.ClientPage)
                .ToListAsync();
           

            List<SelectListItem> assignClientPageOptions = new List<SelectListItem>();
                using (SqlConnection conn = Connection)
                    {
                        conn.Open();
                        using (SqlCommand cmd = conn.CreateCommand())
                        {
                            cmd.CommandText = @"SELECT DISTINCT cp.Id, cp.Name
                                FROM ClientPages cp LEFT JOIN ClientPageUsers cpu ON cpu.ClientPageId = cp.Id
                                WHERE cpu.Id IS NULL 
                                OR cpu.UserId != @id
                                AND cpu.ClientPageId NOT IN
                                (SELECT cpu.ClientPageId
                                FROM ClientPageUsers cpu WHERE cpu.UserId = @id);
                            ";
                            
                            cmd.Parameters.Add(new SqlParameter("@id", id));

                            SqlDataReader reader = cmd.ExecuteReader();

                    while (reader.Read())
                    {                      
                        if (!reader.IsDBNull(reader.GetOrdinal("Name")))
                        {
                            var clientPageName = reader.GetString(reader.GetOrdinal("Name"));
                            var clientPageId = reader.GetInt32(reader.GetOrdinal("Id"));
                            SelectListItem selectListItem = new SelectListItem(clientPageName, clientPageId.ToString());
                            assignClientPageOptions.Add(selectListItem);
                        };
                    }

                    reader.Close();
                }
            }
                
            assignClientPageOptions.Insert(0, new SelectListItem
            {
                Text = "Choose Client Page to assign....",
                Value = "0"
            });
            var viewModel = new EditMarketingUserViewModel()
            {
                User = user,
                UserTypeId = user.UserTypeId,
                UserTypeOptions = userTypeOptions,
                AssignedClientPages = assignedClientPages,
                ClientPageOptions = assignClientPageOptions,
                UserId = id
                
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditMarketingUser(EditMarketingUserViewModel viewModel)
        {

            var clientPageUser = viewModel.ClientPageUser;
            var userId = viewModel.UserId;
            var userToEdit = await _context.ApplicationUsers.Where(u => u.Id == userId).FirstOrDefaultAsync();
            ModelState.Remove("User.FirstName");
            ModelState.Remove("User.LastName");
            if (ModelState.IsValid)
            {
                if (clientPageUser.ClientPageId != 0)
                {
                    clientPageUser.UserId = userId;
                    _context.Update(clientPageUser);
                    await _context.SaveChangesAsync();
                }
                if (userToEdit.UserTypeId != viewModel.UserTypeId)
                {
                    userToEdit.UserTypeId = viewModel.UserTypeId;
                    _context.Update(userToEdit);
                    await _context.SaveChangesAsync();

                }
                return RedirectToAction("MarketingUserDetails", new { Id = viewModel.UserId });
            }
            return View(viewModel);
        }

        // GET: ClientPageUsers/UnassignClientPage/5
        public async Task<IActionResult> UnassignClientPage(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var clientPageUser = await _context.ClientPageUsers
                .Include(cp => cp.ClientPage)
                .FirstOrDefaultAsync(m => m.Id == id);

            var assignedUsers = await _context.ClientPageUsers
                .Include(cpu => cpu.User)
                .Where(cpu => cpu.ClientPageId == clientPageUser.ClientPageId)
                .Select(cpu => cpu.User)
                .ToListAsync();

            clientPageUser.ClientPage.Users = assignedUsers;
            
            if (clientPageUser == null)
            {
                return NotFound();
            }

            return View(clientPageUser);
        }

        // POST: ClientPages/Delete/5
        [HttpPost, ActionName("UnassignClientPage")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UnassignClientPageConfirmed(int id)
        {
            var clientPageUser = await _context.ClientPageUsers.FindAsync(id);                              
            _context.ClientPageUsers.Remove(clientPageUser);
            await _context.SaveChangesAsync();
            return RedirectToAction("MarketingUserDetails", new { Id = clientPageUser.UserId });
        }

       
    }
}

BackendCapstone/Views/ApplicationUsers/ClientUserDetails.cshtml
@model BackendCapstone.Models.ApplicationUser

@{
    ViewData["Title"] = "Details";
}



<div>
    
    <div style="display:flex; border-radius: 5px; flex-direction:row; align-items:center;">
        <img style="width:70px; height: 70px; border-radius: 50%;" src="~/images/@Model.ImgPath" asp-append-version="true" />
        <h1 style="margin: 0 15px;">@Model.FirstName @Model.LastName</h1>
    </div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>      
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
</div>
<div>
    <a href="javascript:history.go(-1)">Back to Previous Page</a>
</div>

BackendCapstone/Views/ApplicationUsers/EditMarketingUser.cshtml
@model BackendCapstone.Models.ApplicationUserViewModels.EditMarketingUserViewModel

@{
    ViewData["Title"] = "EditMarketingUser";
}


<h1>@Model.User.FirstName @Model.User.LastName</h1>

<div>
    <h4>Edit User</h4>
    <hr />
    <div class="editContainer">
        <div style="margin: 0 15px 0 0">
            <img class="editImg" asp-append-version="true" src="~/images/@Model.User.ImgPath"/>
        </div>
        <form asp-action="EditMarketingUser" method="post" class="editForm">
            <div class="form-group">
                <label asp-for="UserTypeId"></label>
                <select asp-for="UserTypeId" class="form-control" asp-items="Model.UserTypeOptions"></select>
            </div>
            <div class="form-group">
                <label asp-for="ClientPageUser"></label>
                <select asp-for="ClientPageUser.ClientPageId" class="form-control" asp-items="Model.ClientPageOptions"></select>
            </div>
            <div class="form-group">
                @Html.HiddenFor(m => m.UserId)
            </div>
            <div class="form-group">
                @Html.HiddenFor(m => m.User.UserTypeId)
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>

    <div>
        <a href="javascript:history.go(-1)">Back to Previous Page</a>
    </div>
</div>

BackendCapstone/Views/ApplicationUsers/MarketingUserDetails.cshtml
@model BackendCapstone.Models.ApplicationUserViewModels.MarketingUserDetailsViewModel
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@{var user = await UserManager.GetUserAsync(User);}

@{
    ViewData["Title"] = "MarketingUserDetails";
}
<div class="repDashContainer">
    <div class="repDasHeader">
        <div class="repUserContainer">
            <img class="repUserImg" src="~/images/@Model.User.ImgPath" asp-append-version="true" />
            <h1 style="margin: 0 15px;">@Model.User.FirstName @Model.User.LastName</h1>
        </div>
    </div>
    <div class="repUserEditContainer">
        <div class="repUserEdit">
            <a asp-route-id=@Model.User.Id asp-controller="ApplicationUsers" asp-action="EditMarketingUser">Edit</a>
        </div>
    </div>
</div>
<div>
    <h3>Upcoming Stories</h3>
    <hr />
    <div id="storyBoardsList" class="storyBoardCardsContainer">

        @*  Use for loop to render unique form elements and ids for each StoryBoard. *@
        @foreach (var item in Model.StoryBoards)
        {
            @*  StoryBoard and Chat container *@
            <div class="repStoryContainer">

                @*  StoryBoard *@
                <div class="repStory">

                    @*  StoryBoard Header *@
                    <div class="repStoryHeader">
                        <p style="margin: 10px 0 0 0">
                            <em>@item.PostDateTime</em>
                        </p>
                        <div id="approvalBox--@item.Id" class="approvalBox">
                            @if (item.IsApproved == true)
                            {
                                <img id="approvalCheck--@item.Id" class="approvalCheckImg" src="~/images/checkmark.png" />
                            }
                        </div>
                    </div>

                    @*  StoryBoard Client Info *@
                    <div class="repStoryClient">
                        <img class="repStoryClientImg" src="~/images/@item.ImgPath" asp-append-version="true" />
                        <p><strong>@item.ClientPage.Name</strong></p>
                    </div>
                    <div>
                        <img class="repStoryImg" asp-append-version="true" src="~/images/@item.ImgPath" />
                    </div>
                    <div>
                        <p>
                            <strong>@item.ClientPage.Name</strong>&nbsp;@item.Text
                        </p>
                    </div>
                    <div class="editDeleteContainer">
                        <a asp-route-id=@item.Id asp-controller="StoryBoards" asp-action="Edit">Edit</a>&nbsp;|&nbsp;
                        <a asp-route-id=@item.Id asp-controller="StoryBoards" asp-action="Delete">Delete</a>
                    </div>
                </div>
            </div>
        }
    </div>
    <hr />

    <h3>Client Pages</h3>
    <div class="clientPagesContainer">
        @foreach (var item in Model.ClientPageUsers)
        {

            <div class="clientPageCard">
                <a class="clientPageLink" asp-controller="ClientPages" asp-action="Details" asp-route-id="@item.ClientPage.Id">
                    <div>
                        <img class="clientPageCardImg" asp-append-version="true" src="~/images/@item.ClientPage.ImgPath" />
                    </div>
                    <div class="clientPageCardName">
                        <h5>
                            @Html.DisplayFor(modelItem => item.ClientPage.Name)
                        </h5>
                    </div>
                </a>
                @if (user.UserTypeId == 1)
                {
                    <div class="editDeleteContainer">
                        <a asp-action="UnassignClientPage" asp-route-id=@item.Id>Unassign</a>
                    </div>
                }
            </div>
        }
    </div>
</div>
<div>
    <a asp-controller="Home" asp-action="AdminHome">Back to Dashboard</a>
</div>

BackendCapstone/Views/ApplicationUsers/UnassignClientPage.cshtml
@model BackendCapstone.Models.ClientPageUser

@{
    ViewData["Title"] = "UnassignClientPage";
}

<h1>Client Page</h1>

<h3>Are you sure you want to unassign this client?</h3>
<div>
    <h4>Client Page</h4>
    <hr />
    <div style="display: flex; margin: 30px; width:1000px; height:315px; background-color:#FAFAFA; border-radius:3px;">    
            <div style="margin: 0 15px 0 0;">
                <img style="width:300px; height:315px;" asp-append-version="true" src="~/images/@Model.ClientPage.ImgPath" />
            </div>
            <div style="margin:15px 0 0 0;">
                
                <h5>
                    @Html.DisplayFor(modelItem => Model.ClientPage.Name)
                </h5>
                <hr />
                <p>
                    @Html.DisplayFor(modelItem => Model.ClientPage.Description)
                </p>
                <hr />

                <div style="display:flex; flex-direction:row;">
                    @foreach (var item in Model.ClientPage.Users)
                    {
                        <div style="margin:10px 10px 10px 10px;">
                            <a asp-controller="ApplicationUsers" asp-action="MarketingUserDetails" asp-route-id="@item.Id">
                                <div style="display: flex; flex-direction: column; justify-content: center;">
                                    <img style="width:70px; height: 70px; border-radius: 50%;" src="~/images/@item.ImgPath" asp-append-version="true" />
                                    <p>@item.FirstName @item.LastName</p>
                                </div>
                            </a>
                        </div>
                    }
                </div>
            </div>      
    </div>
    <div>
        <form asp-action="UnassignClientPage">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Unassign" class="btn btn-danger" /> |
            <a asp-action="MarketingUserDetails" asp-route-id=@Model.UserId>Back to User Details</a>
        </form>
    </div>
</div>